name: benchdogworkshop
favicon: null
layout_spectrum: 0.3296664992813021
typography_spectrum: 0.0349958420265466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9316179456654936
  lightness: 0.9398616736289114
  saturation: 0.7491464961785823
  rhythmicContrast: 0.35206681373529136
purpose: []
